import {
  ArrowDown,
  ArrowUp,
  ArrowUpDown,
  ArrowUpRight,
  AlignCenter,
  AlignLeft,
  AlignRight,
  Archive,
  BatteryFull,
  Calendar,
  CalendarDays,
  BellRing,
  Check,
  Columns3,
  ClipboardPaste,
  CircleCheck,
  CloudCheck,
  CloudOff,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Crosshair,
  CircleUserRound,
  Clock,
  Copy,
  Download,
  BellOff,
  Ellipsis,
  EllipsisVertical,
  Eye,
  EyeOff,
  Flag,
  File,
  FileArchive,
  FileImage,
  FileText,
  FileType,
  Filter,
  Folder,
  FolderCheck,
  FolderOpen,
  GripVertical,
  Grid2x2,
  House,
  Inbox,
  Info,
  Minus,
  Menu,
  Mail,
  Layers,
  List,
  Monitor,
  Maximize,
  MapPin,
  MousePointer2,
  MoveUpRight,
  Palette,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  Pipette,
  Plus,
  Search,
  RotateCcw,
  Scissors,
  Settings,
  Share2,
  Star,
  TriangleAlert,
  Trash,
  Trash2,
  UsersRound,
  Volume2,
  VolumeX,
  Wifi,
  SlidersHorizontal,
  X,
  createIcons,
} from "lucide";
import { siApple, siGoogle } from "simple-icons";

const lucideIcons = {
  ArrowDown,
  ArrowUp,
  ArrowUpDown,
  ArrowUpRight,
  AlignCenter,
  AlignLeft,
  AlignRight,
  Archive,
  BatteryFull,
  Calendar,
  CalendarDays,
  BellRing,
  Check,
  Columns3,
  ClipboardPaste,
  CircleCheck,
  CloudCheck,
  CloudOff,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Crosshair,
  CircleUserRound,
  Clock,
  Copy,
  Download,
  BellOff,
  Ellipsis,
  EllipsisVertical,
  Eye,
  EyeOff,
  Flag,
  File,
  FileArchive,
  FileImage,
  FileText,
  FileType,
  Filter,
  Folder,
  FolderCheck,
  FolderOpen,
  GripVertical,
  Grid2x2,
  House,
  Inbox,
  Info,
  Minus,
  Menu,
  Mail,
  Layers,
  List,
  Monitor,
  Maximize,
  MapPin,
  MousePointer2,
  MoveUpRight,
  Palette,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  Pipette,
  Plus,
  Search,
  RotateCcw,
  Scissors,
  Settings,
  Share2,
  Star,
  TriangleAlert,
  Trash,
  Trash2,
  UsersRound,
  Volume2,
  VolumeX,
  Wifi,
  SlidersHorizontal,
  X,
};

const simpleIcons = { apple: siApple, google: siGoogle };

export function renderIcons(root: Element | Document | DocumentFragment = document) {
  createIcons({ icons: lucideIcons, root });

  root.querySelectorAll<HTMLElement>("[data-simple-icon]").forEach((placeholder) => {
    const name = placeholder.dataset.simpleIcon as keyof typeof simpleIcons | undefined;
    const icon = name ? simpleIcons[name] : undefined;
    if (!icon) return;

    const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    svg.setAttribute("viewBox", "0 0 24 24");
    svg.setAttribute("fill", placeholder.dataset.simpleIconColor?.trim() || "currentColor");
    svg.setAttribute("focusable", "false");
    Array.from(placeholder.attributes).forEach(({ name: attributeName, value }) => {
      if (attributeName !== "data-simple-icon" && attributeName !== "data-simple-icon-color") {
        svg.setAttribute(attributeName, value);
      }
    });

    const path = document.createElementNS("http://www.w3.org/2000/svg", "path");
    path.setAttribute("d", icon.path);
    svg.append(path);
    placeholder.replaceWith(svg);
  });
}
